{
  "artifacts": [],
  "command": "main",
  "experiment": {
    "base_dir": "/home/shared/Projects/MAML_Investigation/code/unimodal",
    "dependencies": [
      "numba==0.54.1",
      "numpy==1.20.3",
      "sacred==0.8.2"
    ],
    "mainfile": "testing.py",
    "name": "run",
    "repositories": [
      {
        "commit": "d52d518dc961e06fa4476b82a6ecf38c7a0b98b9",
        "dirty": false,
        "url": "git@github.com:taylanot/PhD.git"
      }
    ],
    "sources": [
      [
        "testing.py",
        "_sources/testing_adadca673789000b0c8bb3cffeb27d09.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"testing.py\", line 94, in main\n    print(move(numba_config))\n",
    "TypeError: not enough arguments: expected 2, got 1\n"
  ],
  "heartbeat": "2021-12-03T16:11:21.379277",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz",
    "hostname": "94fc0411525c",
    "os": [
      "Linux",
      "Linux-5.11.0-40-generic-x86_64-with-glibc2.29"
    ],
    "python_version": "3.8.10"
  },
  "meta": {
    "command": "main",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": "test12",
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2021-12-03T16:11:21.373541",
  "status": "FAILED",
  "stop_time": "2021-12-03T16:11:21.380051"
}